GET https://backend-app-3662c6e6c455.herokuapp.com/api/campaigns
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJldm9uZGV2IiwiaWF0IjoxNjYyNDQyOTc3LCJleHAiOjE2NjI0NDMwMDd9.btgYMgl22L8F1M7wLfxfg4qw5JgOvFkkag4LYAGkroY

###
POST https://backend-app-3662c6e6c455.herokuapp.com/login
Content-Type: application/json

{
  "username": "evondev"
}


###
POST https://backend-app-3662c6e6c455.herokuapp.com/token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJldm9uZGV2IiwiaWF0IjoxNjYyNDQyOTc3LCJleHAiOjE2NjI0NDY1Nzd9.NA7YyGH-lfFHOtYRvbfdOcyaQGr0E6fzc_X2_18kaSM"
}

###
DELETE https://backend-app-3662c6e6c455.herokuapp.com/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJldm9uZGV2IiwiaWF0IjoxNjYyNDQyOTc3LCJleHAiOjE2NjI0NDMwMDd9.btgYMgl22L8F1M7wLfxfg4qw5JgOvFkkag4LYAGkroY

###
POST https://backend-app-3662c6e6c455.herokuapp.com/register
Content-Type: application/json

{
  "username": "evondev",
  "password": "evondev"
}